//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndentGuide {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IndentGuide.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        internal static string Appearance {
            get {
                return ResourceManager.GetString("Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Customize this content type.
        /// </summary>
        internal static string btnCustomizeThisContentType {
            get {
                return ResourceManager.GetString("btnCustomizeThisContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Delete.
        /// </summary>
        internal static string btnThemeDelete {
            get {
                return ResourceManager.GetString("btnThemeDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Save.
        /// </summary>
        internal static string btnThemeSaveAs {
            get {
                return ResourceManager.GetString("btnThemeSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;above.
        /// </summary>
        internal static string chkLineAbove {
            get {
                return ResourceManager.GetString("chkLineAbove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to where they appeared.
        /// </summary>
        internal static string chkLineActual {
            get {
                return ResourceManager.GetString("chkLineActual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;below.
        /// </summary>
        internal static string chkLineBelow {
            get {
                return ResourceManager.GetString("chkLineBelow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for all indents.
        /// </summary>
        internal static string chkLineLogical {
            get {
                return ResourceManager.GetString("chkLineLogical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Default).
        /// </summary>
        internal static string DefaultThemeName {
            get {
                return ResourceManager.GetString("DefaultThemeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No guidelines on empty lines.
        /// </summary>
        internal static string EmptyLineMode_NoGuides {
            get {
                return ResourceManager.GetString("EmptyLineMode_NoGuides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As shown on the previous line.
        /// </summary>
        internal static string EmptyLineMode_SameAsLineAboveActual {
            get {
                return ResourceManager.GetString("EmptyLineMode_SameAsLineAboveActual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As indented on the previous line.
        /// </summary>
        internal static string EmptyLineMode_SameAsLineAboveLogical {
            get {
                return ResourceManager.GetString("EmptyLineMode_SameAsLineAboveLogical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As shown on the following line.
        /// </summary>
        internal static string EmptyLineMode_SameAsLineBelowActual {
            get {
                return ResourceManager.GetString("EmptyLineMode_SameAsLineBelowActual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As indented on the following line.
        /// </summary>
        internal static string EmptyLineMode_SameAsLineBelowLogical {
            get {
                return ResourceManager.GetString("EmptyLineMode_SameAsLineBelowLogical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The mode to use for empty lines. An empty line is either zero-length or contains only whitespace..
        /// </summary>
        internal static string EmptyLineModeDescription {
            get {
                return ResourceManager.GetString("EmptyLineModeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty Line Handling.
        /// </summary>
        internal static string EmptyLineModeDisplayName {
            get {
                return ResourceManager.GetString("EmptyLineModeDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Content Type.
        /// </summary>
        internal static string grpCurrentContentType {
            get {
                return ResourceManager.GetString("grpCurrentContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty Line Behavior.
        /// </summary>
        internal static string grpLineBehavior {
            get {
                return ResourceManager.GetString("grpLineBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Style.
        /// </summary>
        internal static string grpLineStyle {
            get {
                return ResourceManager.GetString("grpLineStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indent Guides Package.
        /// </summary>
        internal static string IndentGuidePackage {
            get {
                return ResourceManager.GetString("IndentGuidePackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Type:.
        /// </summary>
        internal static string lblContentType {
            get {
                return ResourceManager.GetString("lblContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current document&apos;s content type is.
        /// </summary>
        internal static string lblCurrentContentTypeIs {
            get {
                return ResourceManager.GetString("lblCurrentContentTypeIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on the line.
        /// </summary>
        internal static string lblShowAboveBelow {
            get {
                return ResourceManager.GetString("lblShowAboveBelow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show guide lines.
        /// </summary>
        internal static string lblShowActualLogical {
            get {
                return ResourceManager.GetString("lblShowActualLogical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The color of the guide lines..
        /// </summary>
        internal static string LineColorDescription {
            get {
                return ResourceManager.GetString("LineColorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Color.
        /// </summary>
        internal static string LineColorDisplayName {
            get {
                return ResourceManager.GetString("LineColorDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The style of guides to display..
        /// </summary>
        internal static string LineStyleDescription {
            get {
                return ResourceManager.GetString("LineStyleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Style.
        /// </summary>
        internal static string LineStyleDisplayName {
            get {
                return ResourceManager.GetString("LineStyleDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of this theme. Themes are automatically loaded if the name matches the content type of the open document..
        /// </summary>
        internal static string ThemeNameDescription {
            get {
                return ResourceManager.GetString("ThemeNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme Name.
        /// </summary>
        internal static string ThemeNameDisplayName {
            get {
                return ResourceManager.GetString("ThemeNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not available..
        /// </summary>
        internal static string UnknownContentType {
            get {
                return ResourceManager.GetString("UnknownContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True to display indentation guides in all text editors; otherwise, False..
        /// </summary>
        internal static string VisibilityDescription {
            get {
                return ResourceManager.GetString("VisibilityDescription", resourceCulture);
            }
        }
    }
}
