//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndentGuide {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IndentGuide.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        internal static string Appearance {
            get {
                return ResourceManager.GetString("Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No guidelines on empty lines.
        /// </summary>
        internal static string EmptyLineMode_NoGuides {
            get {
                return ResourceManager.GetString("EmptyLineMode_NoGuides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As shown on the previous line.
        /// </summary>
        internal static string EmptyLineMode_SameAsLineAboveActual {
            get {
                return ResourceManager.GetString("EmptyLineMode_SameAsLineAboveActual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As indented on the previous line.
        /// </summary>
        internal static string EmptyLineMode_SameAsLineAboveLogical {
            get {
                return ResourceManager.GetString("EmptyLineMode_SameAsLineAboveLogical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As shown on the following line.
        /// </summary>
        internal static string EmptyLineMode_SameAsLineBelowActual {
            get {
                return ResourceManager.GetString("EmptyLineMode_SameAsLineBelowActual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As indented on the following line.
        /// </summary>
        internal static string EmptyLineMode_SameAsLineBelowLogical {
            get {
                return ResourceManager.GetString("EmptyLineMode_SameAsLineBelowLogical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The mode to use for empty lines. An empty line is either zero-length or contains only whitespace..
        /// </summary>
        internal static string EmptyLineModeDescription {
            get {
                return ResourceManager.GetString("EmptyLineModeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty Line Handling.
        /// </summary>
        internal static string EmptyLineModeDisplayName {
            get {
                return ResourceManager.GetString("EmptyLineModeDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indent Guides Package.
        /// </summary>
        internal static string IndentGuidePackage {
            get {
                return ResourceManager.GetString("IndentGuidePackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The style of guides to display..
        /// </summary>
        internal static string LineStyleDescription {
            get {
                return ResourceManager.GetString("LineStyleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Style.
        /// </summary>
        internal static string LineStyleDisplayName {
            get {
                return ResourceManager.GetString("LineStyleDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True to display indentation guides in all text editors; otherwise, False..
        /// </summary>
        internal static string VisibilityDescription {
            get {
                return ResourceManager.GetString("VisibilityDescription", resourceCulture);
            }
        }
    }
}
